# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0fca9dd4b5dd9f9c144f804a3bd379614da60d80818fead7be2591b65574c14f0a206c60ba51093a68d1343da015c8893b78b2a00d0cf94b09e3986ff15e4b72

test:
  secret_key_base: a62fb9ebcca1a193b59a1a810af85622792711c2efdc937591077ec603186709727ceb13e401bf15f43490f3531e31bfdcbebc373ec0da43cab3956cba033b19

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
